### PR TITLE
Preprocessing-using InceptionV3 issue #25

### PR DESCRIPTION
**Pull request by tarushi98**
Used tensorflow to preprocess the image.Please Check and let me know if any changes are required.

### CODE REVIEW

**Review by vidhi-mody — CHANGES_REQUESTED** [review]
Why are there changes in the README for this issue?

**Comment by tarushi98** [comment]
I had a merge conflict which I fixed using Meld and the final readme file had included all the changes so far 😅I have added the ipynb to the tensorflow implementation branch.

**Review by vidhi-mody — COMMENTED** [review]
This is really nice work @tarushi98 ! 😃 
One suggestion that I have is it would be great if you set the path within the repo itself. This way the code would run on all machines since the path would no longer be specific to your machine. Does this make sense?

**Comment by tarushi98** [comment]
I agree with you but the dataset is not uploaded on the repo . Since we all have to download the dataset anyway , I found it to be computationally cheap to just extract the images from where they have been stored in the system.

**Comment by vidhi-mody** [comment]
@tarushi98 yeah in that case I think this is fine! :)

**Review by vidhi-mody — APPROVED** [review]

**Comment by vidhi-mody** [comment]
@sauravraghuvanshi looks good to me! It would be great if you could review this PR once too. I think we should merge this

**Comment by sauravraghuvanshi** [comment]
Great work @tarushi98 🔥🔥

**Pull request merged**
