### PR TITLE
Initialized COCO API

### PR DESCRIPTION
**Pull request by ChaoticBlack**
The path specified was wrong. Changed it to '/Udacity-Computer-Vision-Nanodegree-Program/project_2_image_captioning_project/cocoapi/'  

After downloading the dataset the images should be unziped and stored in a new folder called "images" inside the cocoapi directory, Similarly annotations should be unzipped and stored in "annotations" folder in the cocoapi directory

### CODE REVIEW

**Comment by sauravraghuvanshi** [comment]
You got it right as I just wanted to check whether the participant has the basic file location knowledge or not.

**Comment by ChaoticBlack** [comment]
> You got it right as I just wanted to check whether the participant has the basic file location knowledge or not.

Thank you!
So what's next?

**Comment by sauravraghuvanshi** [comment]
Even though you got it right but you have to download annotations file( I can't able to upload it as the file is big to upload on GitHub) and you have to run the code to check whether it is working or not before creating the pull request.

**Comment by ChaoticBlack** [comment]
I'm having issues downloading such a huge file, once that is done, I'll test the code!
Hopefully I'll be able to do that by tomorrow!

**Comment by sauravraghuvanshi** [comment]
Sure, we have flexible time to create PR request.

**Pull request closed without merging**
