### PR TITLE
Added The File To Split Data Into Training And Test Sets !

### PR DESCRIPTION
**Pull request by deepeshgarg09**

### CODE REVIEW

**Review by vidhi-mody — CHANGES_REQUESTED** [review]
Only push files associated with this PR. Please remove the other files.

**Comment by deepeshgarg09** [comment]
Done ! Please Review That !

**Review by vidhi-mody — APPROVED** [review]

**Comment by vidhi-mody** [comment]
@deepeshgarg09 please resolve the merge conflicts!
Let me know if you need any help

**Comment by deepeshgarg09** [comment]
Done !!

**Pull request merged**
