### PR TITLE
Added The CNN Model To Implement COCO Dataset And Added The Python File To Initialize COCO API.

### PR DESCRIPTION
**Pull request by deepeshgarg09**

### CODE REVIEW

**Review by vidhi-mody — APPROVED** [review]
Looks good to me!

**Comment by deepeshgarg09** [comment]
Is It Stiil On Review ?

**Review by vidhi-mody — APPROVED** [review]
It would be better if you create separate PR's for separate issues!

**Comment by deepeshgarg09** [comment]
Okay, I will keep it in mind from the next time.

**Pull request merged**
