### PR TITLE
Create DEVELOPERS.md

### PR DESCRIPTION
**Pull request by tarunjain1st**
done with DEVELOPERS.md file

### CODE REVIEW

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
It is ready to merge. Squash all your commits then I  will merge it.

**Comment by tarunjain1st** [comment]
what i have to do for that

**Review by srimanikantapalakollu — COMMENTED** [review]
Learn how to squash the commits on youtube.

**Comment by tarunjain1st** [comment]
done, is this fine.

**Review by vidhi-mody — APPROVED** [review]
Nicely done. Good work adding the links and using markdown!

**Pull request merged**
