### PR TITLE
Continue #13

### PR DESCRIPTION
**Pull request by tarunjain1st**

### CODE REVIEW

**Comment by srimanikantapalakollu** [comment]
There are some merge conflicts with your PR. please make sure to resolve those conflicts in order to merge it into the project.

**Comment by vidhi-mody** [comment]
@tarunjain1st can you resolve the merge conflict? Do you need help with this?

**Comment by tarunjain1st** [comment]
@vidhi-mody yeah sure please help me to figure it out

**Comment by vidhi-mody** [comment]
Implemented in #21

**Pull request closed without merging**
